version: "3.9"
services:
  db:
    image: postgres
    container_name: aewa
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
  web:
    build: .
    container_name: aewa-backend
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/aewa
    ports:
      - "3006:3000"
    depends_on:
      - db